controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'


api:
    resource: '../src/Controller/Api/' # Ajusta el path según tu estructura
    type: attribute
    prefix: '' # No hay prefijo