parameters:
    product_images_directory: '%kernel.project_dir%/public/uploads/product_images'
    profile_images_directory: '%kernel.project_dir%/public/uploads/profile_images'
    category_images_directory: '%kernel.project_dir%/public/uploads/category_images'
    locale: 'en'
    app_locales: 'es|en'
    base_url: 'https://127.0.0.1'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']
    App\Service\Invoice\PaymentInvoice:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
